### PR TITLE
Increase speed of loading dashboard

### PR DESCRIPTION
**Pull request by bkochendorfer**
With a large deployment loading the dashboard was causing my browser tab to crash or I would receive a warning about an unresponsive script. I used Chrome developer tools to profile what was going on and found that the `highlight_violations` function was taking a long time to load. By changing this to an async call the dashboard renders in just a second instead of crashing my browser.

### CODE REVIEW

**Comment by bkochendorfer** [comment]
Not sure the failure here is related to any changes I've made. Can someone verify?

**Comment by l01cd3v** [comment]
The regression tests have nothing to do with the JS code, this is a Travis config issue. Thanks for submitting this fix, a lot of the relevant code has changed in the next version of the tool so I will not merge this commit in master to avoid conflicts. However, I will work on merging this into the new-engine branch. Sorry for the inconvenience, I am try to merge the new-engine branch into master as soon as possible to avoid working on multiple branches.

**Comment by l01cd3v** [comment]
So I just merged all the new-engine branch into master. Dashboards should automatically be loaded now, and I don't expect them to take long. Violations are only highlighted when following a link from the dashboard, I think I will use your code to restore the highlighting when loading resources. Can you let me know if the new code is slow when run on a large account?

Thanks !

**Comment by bkochendorfer** [comment]
I tried to run your changes to test and I now get the following error. Unable to confirm speed differences at this point.

```
Traceback (most recent call last):
  File "Scout2.py", line 233, in <module>
    sys.exit(main(args))
  File "Scout2.py", line 168, in main
    aws_config['services'][service]['violations'][rule]['flagged_items'] = len(aws_config['services'][service]['violations'][rule]['items'])
KeyError: 'items'
```

**Comment by l01cd3v** [comment]
Which command did you use? Did you update opinel (pip install -r requirements.txt)?

**Comment by bkochendorfer** [comment]
Yes, updated. 
```
python Scout2.py --csv-credentials my_cred_path.csv
```

**Comment by l01cd3v** [comment]
Can you try a run with --debug and share the whole console output please?

**Comment by bkochendorfer** [comment]
Odd, I tried again and didn't get that error. Let's assume I did something incorrect on my end. I tested and the dashboard is indeed much snappier now. I'll go ahead and close this out! Thanks

**Comment by l01cd3v** [comment]
Thanks ! Loading the body may still be slow and highlighting does not happen as much as before, but I'll definitely use your code to restore that functionality at some point !

**Pull request closed without merging**
